# This file was generated by GoReleaser. DO NOT EDIT.
cask "seqtoid" do
  version "6.1.4"

  on_macos do
    on_intel do
      sha256 "50eaed240ad6198435347f6d6581cec5e9d1a602515a5b57f67edc8df9441eca"
      url "https://github.com/IT-Academic-Research-Services/seqtoid-cli/releases/download/v#{version}/seqtoid-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ff0bf72338e4d9f05730635649c216cd0c73673039837b42663f4f94296ceefc"
      url "https://github.com/IT-Academic-Research-Services/seqtoid-cli/releases/download/v#{version}/seqtoid-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2d7c893edabcac1111ea21dbcd43f1640b8f9e58ae4d545502e2da6a72a88bab"
      url "https://github.com/IT-Academic-Research-Services/seqtoid-cli/releases/download/v#{version}/seqtoid-cli_linux_amd64.tar.gz"
    end
  end

  name "seqtoid"
  desc "A CLI for uploading samples to SeqToID"
  homepage "https://github.com/IT-Academic-Research-Services/seqtoid-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "seqtoid"
  bash_completion "completions/bash/seqtoid"
  fish_completion "completions/fish/seqtoid"
  zsh_completion "completions/zsh/seqtoid"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/seqtoid")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/seqtoid"]
    end
  end

  # No zap stanza required

end
