# This file was generated by GoReleaser. DO NOT EDIT.
cask "seqtoid" do
  version "6.2.2"

  on_macos do
    on_arm do
      sha256 "0323c3751a359f11d53d115adc7dc4e35c21297b6e75986ff8b34d9f3a5a50da"
      url "https://github.com/IT-Academic-Research-Services/seqtoid-cli/releases/download/v#{version}/seqtoid-cli_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7b6a267c190f67caebbb33d6d5683a207dc02beacc12506d40b80b3655388ff0"
      url "https://github.com/IT-Academic-Research-Services/seqtoid-cli/releases/download/v#{version}/seqtoid-cli_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9f1defba616f68d624f649973ea61e99e26a1cd0c67e951c80af3222c34e1b95"
      url "https://github.com/IT-Academic-Research-Services/seqtoid-cli/releases/download/v#{version}/seqtoid-cli_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7e9be7cae9b306fab6f87b6f895676bad71ec20bd62033bbe82b2eab618cbcdf"
      url "https://github.com/IT-Academic-Research-Services/seqtoid-cli/releases/download/v#{version}/seqtoid-cli_linux_amd64.tar.gz"
    end
  end

  name "seqtoid"
  desc "A CLI for uploading samples to SeqToID"
  homepage "https://github.com/IT-Academic-Research-Services/seqtoid-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "seqtoid"
  bash_completion "completions/bash/seqtoid"
  fish_completion "completions/fish/seqtoid"
  zsh_completion "completions/zsh/seqtoid"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/seqtoid")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/seqtoid"]
    end
  end

  # No zap stanza required
end
