# This file was generated by GoReleaser. DO NOT EDIT.
cask "seqtoid" do
  version "6.1.5"

  on_macos do
    on_intel do
      sha256 "a9b1de5bfd3e3a9b0e9d9189c5f66881e1eb9bb1ba0808b077b7376f46368872"
      url "https://github.com/IT-Academic-Research-Services/seqtoid-cli/releases/download/v#{version}/seqtoid-cli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3cdded71bf8b5d78b45ce89671acb2df2a58bcf03161e15d1c9ab783f9026557"
      url "https://github.com/IT-Academic-Research-Services/seqtoid-cli/releases/download/v#{version}/seqtoid-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c288ab9851f6eabb15b4d6469f252bf669c884a7434ca1192b7fb1fb77c5a5c0"
      url "https://github.com/IT-Academic-Research-Services/seqtoid-cli/releases/download/v#{version}/seqtoid-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "37b2c1c3c43763cb8acf5ff8fe74706255628b6f160816e4c25f5fffca80b5c6"
      url "https://github.com/IT-Academic-Research-Services/seqtoid-cli/releases/download/v#{version}/seqtoid-cli_linux_arm64.tar.gz"
    end
  end

  name "seqtoid"
  desc "A CLI for uploading samples to SeqToID"
  homepage "https://github.com/IT-Academic-Research-Services/seqtoid-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "seqtoid"
  bash_completion "completions/bash/seqtoid"
  fish_completion "completions/fish/seqtoid"
  zsh_completion "completions/zsh/seqtoid"

  postflight do
    if OS.mac? && File.exist?("#{staged_path}/seqtoid")
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/seqtoid"]
    end
  end

  # No zap stanza required

end
